# Changes here will be overwritten by Copier
_commit: v0.1-16-g299edf9
_src_path: git@gitlab.pi.planetinnovation.com.au:degraves/template/micropython_library_template.git
gitlab_tag: aws-525-degraves
library_description: MicroPython driver for FT24CxxA I2C EEPROM family (1KB-8KB)
library_name: micropython_ft24cxxa
single_file_module: true
